### ISSUE TITLE
tcmu-runner-0.9.1/api.c:481: bad call to snprintf ?

### ISSUE THREAD

**Issue by dcb314** [agrover/tcmu-runner#14]
In function 'snprintf',
    inlined from 'tcmu_emulate_evpd_inquiry' at /home/dcb/rpmbuild/BUILD/tcmu-runner-0.9.1/api.c:481:9:
/usr/include/bits/stdio2.h:64:10: warning: call to __builtin___snprintf_chk will always overflow destination buffer

Source code is

       len = snprintf(&ptr[12], sizeof(data) - 12, "%s", wwn);

maybe better code

       len = snprintf(&ptr[12], sizeof(data) - 16, "%s", wwn);

**Comment by agrover** [comment]
Nice find, thanks! (Hmm, I wonder why I didn't see this warning...?)

**Comment by dcb314** [comment]
>I wonder why I didn't see this warning...?

When compiling with gcc, try adding -D_FORTIFY_SOURCE=2 to
the compiler command line. Fedora Linux does this.

**Comment by agrover** [comment]
thanks for the tip, will try! :+1:
