### ISSUE TITLE
FALLOC_FL_ZERO_RANGE defined in <linux/falloc.h> on my system

### ISSUE THREAD

**Issue by gonzoleeman** [agrover/tcmu-runner#52]
I am compiling the latest on openSUSE-Leap-42.1, and the file cow.c makes a call to fallocate() using the define FALLOC_FL_ZERO_RANGE, but this file is defined in <linux/falloc.h>.

I have prepared a patch that makes it possible to include this file, if needed, via the option "-DHAVE_LINUX_FALLOC:string=true" to cmake.

**Comment by agrover** [comment]
merged, thanks!
